# Generated by Django 2.2.7 on 2019-11-06 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='postal_code',
        ),
    ]
