# Generated by Django 2.2.7 on 2019-11-09 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import internship_finder.announcements.models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(upload_to=internship_finder.announcements.models.get_cv_path, verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
